=== mrthinger/hardware-hack/opentrons/shared-data/deck/schemas/4.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "opentronsDeckSchemaV4",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "coordinates": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y", "z"],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    },
    "unitVector": {
      "type": "array",
      "description": "Array of 3 unit directions, [x, y, z]",
      "items": {
        "type": "number",
        "enum": [1, -1]
      },
      "minItems": 3,
      "maxItems": 3
    },
    "boundingBox": {
      "type": "object",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "xDimension": { "$ref": "#/definitions/positiveNumber" },
        "yDimension": { "$ref": "#/definitions/positiveNumber" },
        "zDimension": { "$ref": "#/definitions/positiveNumber" }
      }
    }
  },
  "description": "Deck specifications, where x,y,z (0,0,0) is at front the bottom left corner.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "otId",
    "schemaVersion",
    "cornerOffsetFromOrigin",
    "dimensions",
    "metadata",
    "robot",
    "locations",
    "cutoutFixtures"
  ],
  "properties": {
    "otId": {
      "description": "Unique internal ID generated using UUID",
      "type": "string"
    },
    "schemaVersion": {
      "description": "Schema version of a deck is a single integer",
      "enum": [4]
    },
    "cornerOffsetFromOrigin": {
      "$ref": "#/definitions/xyzArray",
      "description": "Position of left-front-bottom corner of entire deck to robot coordinate system origin"
    },
    "dimensions": {
      "$ref": "#/definitions/xyzArray",
      "description": "Outer dimensions of a deck bounding box"
    },
    "metadata": {
      "description": "Optional metadata about the Deck",
      "type": "object",
      "properties": {
        "displayName": {
          "description": "A short, human-readable name for the deck",
          "type": "string"
        },
        "tags": {
          "description": "Tags to be used in searching for this deck",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "robot": {
      "type": "object",
      "required": ["model"],
      "properties": {
        "model": {
          "description": "Model of the robot",
          "type": "string",
          "enum": ["OT-2 Standard", "OT-3 Standard"]
        }
      }
    },
    "locations": {
      "type": "object",
      "required": [
        "addressableAreas",
        "calibrationPoints",
        "cutouts",
        "legacyFixtures"
      ],
      "properties": {
        "addressableAreas": {
          "type": "array",
          "items": {
            "type": "object",
            "description": "An addressable area is a named area in 3D space that the robot can interact with--for example, as a place to drop tips, or hold a labware.",
            "required": [
              "id",
              "areaType",
              "offsetFromCutoutFixture",
              "boundingBox",
              "displayName"
            ],
            "properties": {
              "id": {
                "description": "Unique identifier for slot",
                "type": "string"
              },
              "areaType": {
                "description": "The type of addressable area, defining allowed behavior.",
                "type": "string",
                "enum": [
                  "slot",
                  "stagingSlot",
                  "movableTrash",
                  "fixedTrash",
                  "wasteChute"
                ]
              },
              "offsetFromCutoutFixture": {
                "$ref": "#/definitions/xyzArray",
                "description": "The offset from the origin of the cutout fixture that's providing this addressable area (which is currently identical to the position of the underlying cutout), to the -x, -y, -z corner of this addressable area's bounding box."
              },
              "matingSurfaceUnitVector": {
                "$ref": "#/definitions/unitVector",
                "description": "An optional diagonal direction of force, defined by spring location, which governs the mating surface of objects placed in this addressable area. Meant to be used when this addressable area is a slot."
              },
              "boundingBox": {
                "description": "The active area (both pipettes can reach) of this addressable area.",
                "$ref": "#/definitions/boundingBox"
              },
              "displayName": {
                "description": "A human-readable nickname for this area e.g. \"Slot A1\" or \"Trash Bin in A1\"",
                "type": "string"
              },
              "compatibleModuleTypes": {
                "description": "An array of module types that can be placed in this area. The module type names can be found in the moduleType field of a module definition.",
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "ableToDropTips": {
                "description": "Whether tips are allowed to be dropped into this area. If `true`, the top-center of the `boundingBox` should be a good location for the bottom-center of all the tips when they're dropped.",
                "type": "boolean"
              },
              "ableToDropLabware": {
                "description": "Whether labware is allowed to be dropped (different from being placed) into this area. If `true`, the top-center of the `boundingBox` should be a good location for the bottom-center of the labware when it's dropped.",
                "type": "boolean"
              }
            }
          }
        },
        "calibrationPoints": {
          "type": "array",
          "description": "Key points for deck calibration",
          "items": {
            "type": "object",
            "required": ["id", "position", "displayName"],
            "properties": {
              "id": {
                "description": "Unique identifier for calibration point",
                "type": "string"
              },
              "position": {
                "$ref": "#/definitions/xyzArray"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this point Eg \"Slot 3 Cross\" or \"Slot 1 Dot\"",
                "type": "string"
              }
            }
          }
        },
        "cutouts": {
          "type": "array",
          "description": "The machined cutout slots on the deck surface.",
          "items": {
            "type": "object",
            "required": ["id", "position", "displayName"],
            "properties": {
              "id": {
                "description": "Unique identifier for the cutout",
                "type": "string"
              },
              "position": {
                "description": "Absolute position of the cutout",
                "$ref": "#/definitions/xyzArray"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this cutout e.g. \"Cutout A1\"",
                "type": "string"
              }
            }
          }
        },
        "legacyFixtures": {
          "type": "array",
          "description": "Fixed position objects on the deck.",
          "items": {
            "type": "object",
            "required": ["id", "displayName"],
            "properties": {
              "id": {
                "description": "Unique identifier for fixed object",
                "type": "string"
              },
              "labware": {
                "description": "Valid labware loadName for fixed object",
                "type": "string"
              },
              "slot": {
                "description": "Slot location of the fixed object",
                "type": "string"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this fixture Eg \"Tall Fixed Trash\" or \"Short Fixed Trash\"",
                "type": "string"
              }
            }
          }
        }
      }
    },
    "cutoutFixtures": {
      "type": "array",
      "items": {
        "description": "A cutout fixture is a physical thing that can be mounted onto one of the deck cutouts.",
        "type": "object",
        "required": [
          "id",
          "mayMountTo",
          "displayName",
          "providesAddressableAreas",
          "height"
        ],
        "properties": {
          "id": {
            "description": "Unique identifier for the cutout fixture.",
            "type": "string"
          },
          "mayMountTo": {
            "description": "A list of compatible cutouts this fixture may be mounted to. These must match `id`s in `cutouts`.",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "displayName": {
            "description": "A human-readable nickname for this area e.g. \"Standard Right Slot\" or \"Slot With Movable Trash\"",
            "type": "string"
          },
          "providesAddressableAreas": {
            "description": "The addressable areas that this cutout fixture provides, when it's mounted. It can provide different addressable areas depending on where it's mounted. Keys must match values from this object's `mayMountTo`. Values must match `id`s from `addressableAreas`.",
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "height": {
            "description": "The vertical distance (mm) from the cutout fixture's origin to its tallest physical feature that an instrument could collide with.",
            "type": "number"
          }
        }
      }
    },
    "gripperOffsets": {
      "type": "object",
      "description": "Offsets to be added when calculating the coordinates a gripper should go to when picking up or dropping a labware on this deck.",
      "properties": {
        "default": {
          "type": "object",
          "properties": {
            "pickUpOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate pick-up coordinates of a labware placed on this deck."
            },
            "dropOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate drop coordinates of a labware placed on this deck."
            }
          },
          "required": ["pickUpOffset", "dropOffset"]
        }
      },
      "required": ["default"]
    }
  }
}

=== mrthinger/hardware-hack/opentrons/shared-data/deck/definitions/4/ot2_standard.json
{
  "otId": "ot2_standard",
  "schemaVersion": 4,
  "cornerOffsetFromOrigin": [-115.65, -68.03, 0],
  "dimensions": [624.3, 565.2, 0],
  "metadata": {
    "displayName": "OT-2 Standard Deck",
    "tags": ["ot2", "12 slots", "standard"]
  },
  "robot": {
    "model": "OT-2 Standard"
  },
  "locations": {
    "addressableAreas": [
      {
        "id": "1",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 1",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "2",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 2",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "3",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 3",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "4",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 4",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "5",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 5",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "6",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 6",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "7",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 7",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "thermocyclerModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "8",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 8",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "9",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 9",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "10",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 10",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "11",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 11",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "12",
        "areaType": "slot",
        "offsetFromCutoutFixture": [0.0, 0.0, 0.0],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 12",
        "compatibleModuleTypes": []
      },
      {
        "id": "fixedTrash",
        "areaType": "fixedTrash",
        "offsetFromCutoutFixture": [29.285, -2.835, 0],
        "boundingBox": {
          "xDimension": 107.11,
          "yDimension": 165.67,
          "zDimension": 82
        },
        "displayName": "Slot 12/Fixed Trash",
        "ableToDropTips": true
      }
    ],
    "cutouts": [
      {
        "id": "cutout1",
        "position": [0.0, 0.0, 0.0],
        "displayName": "Cutout 1"
      },
      {
        "id": "cutout2",
        "position": [132.5, 0.0, 0.0],
        "displayName": "Cutout 2"
      },
      {
        "id": "cutout3",
        "position": [265.0, 0.0, 0.0],
        "displayName": "Cutout 3"
      },
      {
        "id": "cutout4",
        "position": [0.0, 90.5, 0.0],
        "displayName": "Cutout 4"
      },
      {
        "id": "cutout5",
        "position": [132.5, 90.5, 0.0],
        "displayName": "Cutout 5"
      },
      {
        "id": "cutout6",
        "position": [265.0, 90.5, 0.0],
        "displayName": "Cutout 6"
      },
      {
        "id": "cutout7",
        "position": [0.0, 181.0, 0.0],
        "displayName": "Cutout 7"
      },
      {
        "id": "cutout8",
        "position": [132.5, 181.0, 0.0],
        "displayName": "Cutout 8"
      },
      {
        "id": "cutout9",
        "position": [265.0, 181.0, 0.0],
        "displayName": "Cutout 9"
      },
      {
        "id": "cutout10",
        "position": [0.0, 271.5, 0.0],
        "displayName": "Slot 10"
      },
      {
        "id": "cutout11",
        "position": [132.5, 271.5, 0.0],
        "displayName": "Cutout 11"
      },
      {
        "id": "cutout12",
        "position": [265.0, 271.5, 0.0],
        "displayName": "Cutout 12"
      }
    ],
    "calibrationPoints": [
      {
        "id": "1BLC",
        "position": [12.13, 9.0, 0.0],
        "displayName": "Slot 1 Bottom Left Cross"
      },
      {
        "id": "3BRC",
        "position": [380.87, 9.0, 0.0],
        "displayName": "Slot 3 Bottom Right Cross"
      },
      {
        "id": "7TLC",
        "position": [12.13, 258.0, 0.0],
        "displayName": "Slot 7 Top Left Cross"
      },
      {
        "id": "9TRC",
        "position": [380.87, 258.0, 0.0],
        "displayName": "Slot 9 Top Right Cross"
      },
      {
        "id": "10TLC",
        "position": [12.13, 348.5, 0.0],
        "displayName": "Slot 10 Top Left Cross"
      },
      {
        "id": "11TRC",
        "position": [248.37, 348.5, 0.0],
        "displayName": "Slot 11 Top Right Cross"
      },
      {
        "id": "1BLD",
        "position": [12.13, 6.0, 0.0],
        "displayName": "Slot 1 Bottom Left Dot"
      },
      {
        "id": "3BRD",
        "position": [380.87, 6.0, 0.0],
        "displayName": "Slot 3 Bottom Right Dot"
      },
      {
        "id": "7TLD",
        "position": [12.13, 261.0, 0.0],
        "displayName": "Slot 7 Top Left Dot"
      },
      {
        "id": "9TRD",
        "position": [380.87, 261.0, 0.0],
        "displayName": "Slot 9 Top Right Dot"
      },
      {
        "id": "10TLD",
        "position": [12.13, 351.5, 0.0],
        "displayName": "Slot 10 Top Left Dot"
      },
      {
        "id": "11TRD",
        "position": [248.37, 351.5, 0.0],
        "displayName": "Slot 11 Top Right Dot"
      }
    ],
    "legacyFixtures": [
      {
        "id": "fixedTrash",
        "slot": "12",
        "labware": "opentrons_1_trash_1100ml_fixed",
        "displayName": "Fixed Trash"
      }
    ]
  },
  "cutoutFixtures": [
    {
      "id": "singleStandardSlot",
      "mayMountTo": [
        "cutout1",
        "cutout2",
        "cutout3",
        "cutout4",
        "cutout5",
        "cutout6",
        "cutout7",
        "cutout8",
        "cutout9",
        "cutout10",
        "cutout11",
        "cutout12"
      ],
      "displayName": "Standard Slot",
      "providesAddressableAreas": {
        "cutout1": ["1"],
        "cutout2": ["2"],
        "cutout3": ["3"],
        "cutout4": ["4"],
        "cutout5": ["5"],
        "cutout6": ["6"],
        "cutout7": ["7"],
        "cutout8": ["8"],
        "cutout9": ["9"],
        "cutout10": ["10"],
