=== mrthinger/hardware-hack/opentrons/shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "liquidHandlingSpecs": {
      "description": "Object containing linear equations for translating between uL of liquid and mm of plunger travel. There is one linear equation for aspiration and one for dispense",
      "type": "object",
      "required": ["aspirate", "dispense"],
      "additionalProperties": false,
      "properties": {
        "aspirate": { "$ref": "#/definitions/xyzArray" },
        "dispense": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "flowRate": {
      "description": "Object with a default value and optional dict keyed by api level. If API level is unavailable, default is used.",
      "type": "object",
      "required": ["default", "valuesByApiLevel"],
      "properties": {
        "default": {
          "$ref": "#/definitions/positiveNumber",
          "$comment": "The default value of the flowrate"
        },
        "valuesByApiLevel": { "type": "object", "required": [] }
      }
    }
  },
  "type": "object",
  "required": [
    "$otSharedSchema",
    "maxVolume",
    "minVolume",
    "defaultTipracks",
    "supportedTips",
    "defaultTipOverlapDictionary"
  ],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteLiquidPropertiesSchema.json is a reference to this schema."
    },
    "supportedTips": {
      "type": "object",
      "description": "A container of supported tip types",
      "properties": {
        "patternProperties": {
          "description": "Tip specific liquid handling properties for a given pipette. Using the active tip on a pipette, we will look up the pipetting configurations associated with that tip+pipette combo.",
          "type": "object",
          "$comment": "Example key: 't50'",
          "^t[0-9]{2,4}": {
            "required": [
              "defaultAspirateFlowRate",
              "defaultDispenseFlowRate",
              "defaultBlowOutFlowRate",
              "aspirate",
              "dispense"
            ],
            "properties": {
              "defaultAspirateFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultDispenseFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultBlowOutFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultFlowAcceleration": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultTipLength": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultReturnTipHeight": {
                "$ref": "#/definitions/positiveNumber"
              },
              "aspirate": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "dispense": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "uiMaxFlowRate": {
                "$ref": "#/definitions/positiveNumber",
                "$comment": "To be used in frontend applications only since it is the limit-to-lowest-max",
                "description": "An optional number to represent each pipette's supported tip max flow rate for aspirate and dispense. The limit is the lowest max flow rate given all the tip's volumes minus 2% for safety."
              }
            }
          }
        }
      }
    },
    "defaultTipOverlapDictionary": {
      "type": "object",
      "description": "Map of tip overlap values with defaults",
      "required": ["default"],
      "$comment": "Other keys in here should be labware URIs",
      "properties": {
        "default": { "type": "number" }
      },
      "additionalProperties": { "type": "number" }
    },
    "maxVolume": { "$ref": "#/definitions/positiveNumber" },
    "minVolume": { "$ref": "#/definitions/positiveNumber" },
    "defaultTipracks": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== mrthinger/hardware-hack/opentrons/shared-data/pipette/definitions/2/liquid/ninety_six_channel/p1000/default/3_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t50": {
      "uiMaxFlowRate": 194,
      "defaultAspirateFlowRate": {
        "default": 6,
        "valuesByApiLevel": { "2.14": 6 }
      },
      "defaultDispenseFlowRate": {
        "default": 6,
        "valuesByApiLevel": { "2.14": 6 }
      },
      "defaultBlowOutFlowRate": {
        "default": 80,
        "valuesByApiLevel": { "2.14": 80 }
      },
      "defaultFlowAcceleration": 16000.0,
      "defaultTipLength": 57.9,
      "defaultReturnTipHeight": 0.2,
      "aspirate": {
        "default": {
          "1": [
            [1.9733, 2.7039, 5.1258],
            [2.88, 1.0915, 8.3077],
            [3.7642, 0.5906, 9.7502],
            [4.9783, 1.0072, 8.1822],
            [5.9342, 0.2998, 11.7038],
            [6.8708, 0.1887, 12.3626],
            [7.8092, 0.1497, 12.631],
            [8.7525, 0.1275, 12.804],
            [13.4575, 0.0741, 13.2718],
            [22.8675, 0.0296, 13.87],
            [37.0442, 0.0128, 14.2551],
            [55.4792, -0.0013, 14.7754]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [1.9733, 2.7039, 5.1258],
            [2.88, 1.0915, 8.3077],
            [3.7642, 0.5906, 9.7502],
            [4.9783, 1.0072, 8.1822],
            [5.9342, 0.2998, 11.7038],
            [6.8708, 0.1887, 12.3626],
            [7.8092, 0.1497, 12.631],
            [8.7525, 0.1275, 12.804],
            [13.4575, 0.0741, 13.2718],
            [22.8675, 0.0296, 13.87],
            [37.0442, 0.0128, 14.2551],
            [55.4792, -0.0013, 14.7754]
          ]
        }
      },
      "defaultPushOutVolume": 7
    },
    "t200": {
      "uiMaxFlowRate": 194,
      "defaultAspirateFlowRate": {
        "default": 80,
        "valuesByApiLevel": { "2.14": 80 }
      },
      "defaultDispenseFlowRate": {
        "default": 80,
        "valuesByApiLevel": { "2.14": 80 }
      },
      "defaultBlowOutFlowRate": {
        "default": 80,
        "valuesByApiLevel": { "2.14": 80 }
      },
      "defaultFlowAcceleration": 16000.0,
      "defaultTipLength": 58.35,
      "defaultReturnTipHeight": 0.2,
      "aspirate": {
        "default": {
          "1": [
            [1.9331, 3.4604, 3.5588],
            [2.9808, 1.5307, 7.2892],
            [3.9869, 0.825, 9.3926],
            [4.9762, 0.5141, 10.6323],
            [5.9431, 0.3232, 11.5819],
            [6.9223, 0.2644, 11.9317],
            [7.8877, 0.1832, 12.4935],
            [8.8562, 0.1512, 12.7463],
            [47.7169, 0.0281, 13.836],
            [95.63, 0.0007, 15.147],
            [211.1169, 0.0005, 15.1655]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [1.9331, 3.4604, 3.5588],
            [2.9808, 1.5307, 7.2892],
            [3.9869, 0.825, 9.3926],
            [4.9762, 0.5141, 10.6323],
            [5.9431, 0.3232, 11.5819],
            [6.9223, 0.2644, 11.9317],
            [7.8877, 0.1832, 12.4935],
            [8.8562, 0.1512, 12.7463],
            [47.7169, 0.0281, 13.836],
            [95.63, 0.0007, 15.147],
            [211.1169, 0.0005, 15.1655]
          ]
        }
      },
      "defaultPushOutVolume": 5
    },
    "t1000": {
      "uiMaxFlowRate": 187.2,
      "defaultAspirateFlowRate": {
        "default": 160,
        "valuesByApiLevel": { "2.14": 160 }
      },
      "defaultDispenseFlowRate": {
        "default": 160,
        "valuesByApiLevel": { "2.14": 160 }
      },
      "defaultBlowOutFlowRate": {
        "default": 80,
        "valuesByApiLevel": { "2.14": 80 }
      },
      "defaultFlowAcceleration": 16000.0,
      "defaultTipLength": 95.6,
      "defaultReturnTipHeight": 0.2,
      "aspirate": {
        "default": {
          "1": [
            [3.9, 1.789, 5.4283],
            [5.6991, 0.3019, 11.2278],
            [8.5155, 0.2111, 11.7453],
            [13.1482, 0.0858, 12.8124],
            [17.8909, 0.0604, 13.1472],
            [46.0982, 0.0155, 13.9505],
            [93.5618, 0.0046, 14.4523],
            [112.5991, 0.0023, 14.6687],
            [189.5555, 0.002, 14.7035],
            [305.5891, 0.001, 14.887],
            [431.2836, 0.0004, 15.055],
            [625.0209, 0.0003, 15.1309],
            [818.6909, 0.0001, 15.2112],
            [963.9909, 0.0001, 15.2445],
            [992.0791, -0.0005, 15.7723],
            [1012.2118, 0.0007, 14.6701],
            [1037.1873, 0.0005, 14.8072]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [3.9, 1.789, 5.4283],
            [5.6991, 0.3019, 11.2278],
            [8.5155, 0.2111, 11.7453],
            [13.1482, 0.0858, 12.8124],
            [17.8909, 0.0604, 13.1472],
            [46.0982, 0.0155, 13.9505],
            [93.5618, 0.0046, 14.4523],
            [112.5991, 0.0023, 14.6687],
            [189.5555, 0.002, 14.7035],
            [305.5891, 0.001, 14.887],
            [431.2836, 0.0004, 15.055],
            [625.0209, 0.0003, 15.1309],
            [818.6909, 0.0001, 15.2112],
            [963.9909, 0.0001, 15.2445],
            [992.0791, -0.0005, 15.7723],
            [1012.2118, 0.0007, 14.6701],
            [1037.1873, 0.0005, 14.8072]
          ]
        }
      },
      "defaultPushOutVolume": 20
    }
  },
  "defaultTipOverlapDictionary": {
    "default": 10.5,
    "opentrons/opentrons_flex_96_tiprack_50ul/1": 10.5,
    "opentrons/opentrons_flex_96_tiprack_1000ul/1": 10.5,
    "opentrons/opentrons_flex_96_tiprack_200ul/1": 10.5
  },
  "maxVolume": 1000,
  "minVolume": 5,
  "defaultTipracks": [
    "opentrons/opentrons_flex_96_tiprack_1000ul/1",
    "opentrons/opentrons_flex_96_tiprack_200ul/1",
    "opentrons/opentrons_flex_96_tiprack_50ul/1"
  ]
}

=== mrthinger/hardware-hack/opentrons/shared-data/pipette/definitions/2/liquid/single_channel/p50/lowVolumeDefault/3_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t50": {
      "uiMaxFlowRate": 26.7,
      "defaultAspirateFlowRate": {
        "default": 26.7,
        "valuesByApiLevel": { "2.14": 26.7 }
      },
      "defaultDispenseFlowRate": {
        "default": 26.7,
        "valuesByApiLevel": { "2.14": 26.7 }
      },
      "defaultBlowOutFlowRate": {
        "default": 26.7,
        "valuesByApiLevel": { "2.14": 26.7 }
      },
      "defaultFlowAcceleration": 1200.0,
      "defaultTipLength": 57.9,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [0.11, 0.207815, 0.040201],
            [0.65, 0.43933, 0.014735],
            [1.04, 0.256666, 0.133466],
            [1.67, 0.147126, 0.247388],
            [2.45, 0.078774, 0.361536],
            [2.89, 0.042387, 0.450684],
            [3.2, 0.014781, 0.530464],
            [3.79, 0.071819, 0.347944],
            [4.22, 0.051592, 0.424605],
            [4.93, 0.021219, 0.552775],
            [5.81, 0.023461, 0.541725],
            [7.21, 0.008959, 0.625982],
            [8.93, 0.005456, 0.651235],
            [10.0, 0.007108, 0.636489],
            [13.61, 0.002591, 0.681656],
            [26.99, 0.001163, 0.701094],
            [45.25, 0.000207, 0.726887]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.11, 0.207815, 0.040201],
            [0.65, 0.43933, 0.014735],
            [1.04, 0.256666, 0.133466],
            [1.67, 0.147126, 0.247388],
            [2.45, 0.078774, 0.361536],
            [2.89, 0.042387, 0.450684],
            [3.2, 0.014781, 0.530464],
            [3.79, 0.071819, 0.347944],
            [4.22, 0.051592, 0.424605],
            [4.93, 0.021219, 0.552775],
            [5.81, 0.023461, 0.541725],
            [7.21, 0.008959, 0.625982],
            [8.93, 0.005456, 0.651235],
            [10.0, 0.007108, 0.636489],
            [13.61, 0.002591, 0.681656],
            [26.99, 0.001163, 0.701094],
            [45.25, 0.000207, 0.726887]
          ]
        }
      },
      "defaultPushOutVolume": 7
    }
  },
  "defaultTipOverlapDictionary": {
    "default": 10.5,
    "opentrons/opentrons_flex_96_tiprack_50ul/1": 10.5,
    "opentrons/opentrons_flex_96_filtertiprack_50ul/1": 10.5
  },
  "maxVolume": 30,
  "minVolume": 1,
  "defaultTipracks": [
    "opentrons/opentrons_flex_96_tiprack_50ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_50ul/1"
  ]
}
