=== mrthinger/hardware-hack/opentrons/shared-data/protocol/schemas/8.json
{
  "$id": "opentronsProtocolSchemaV8",
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {},

  "type": "object",
  "additionalProperties": false,
  "required": [
    "$otSharedSchema",
    "schemaVersion",
    "metadata",
    "robot",
    "labwareDefinitions",
    "labwareDefinitionSchemaId",
    "commands",
    "commandSchemaId",
    "commandAnnotations",
    "commandAnnotationSchemaId",
    "liquids",
    "liquidSchemaId"
  ],
  "properties": {
    "$otSharedSchema": {
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension.",
      "enum": ["#/protocol/schemas/8"]
    },

    "schemaVersion": {
      "description": "Schema version of a protocol is a single integer",
      "enum": [8]
    },

    "metadata": {
      "description": "Optional metadata about the protocol",
      "type": "object",

      "properties": {
        "protocolName": {
          "description": "A short, human-readable name for the protocol",
          "type": "string"
        },
        "author": {
          "description": "The author or organization who created the protocol",
          "type": "string"
        },
        "description": {
          "description": "A text description of the protocol.",
          "type": ["string", "null"]
        },

        "created": {
          "description": "UNIX timestamp when this file was created",
          "type": "number"
        },
        "lastModified": {
          "description": "UNIX timestamp when this file was last modified",
          "type": ["number", "null"]
        },

        "category": {
          "description": "Category of protocol (eg, \"Basic Pipetting\")",
          "type": ["string", "null"]
        },
        "subcategory": {
          "description": "Subcategory of protocol (eg, \"Cell Plating\")",
          "type": ["string", "null"]
        },
        "tags": {
          "description": "Tags to be used in searching for this protocol",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },

    "designerApplication": {
      "description": "Optional data & metadata not required to execute the protocol, used by the application that created this protocol",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the application that created the protocol. Should be namespaced under the organization or individual who owns the organization, eg \"opentrons/protocol-designer\"",
          "type": "string"
        },
        "version": {
          "description": "Version of the application that created the protocol",
          "type": "string"
        },
        "data": {
          "description": "Any data used by the application that created this protocol",
          "type": "object"
        }
      }
    },

    "robot": {
      "required": ["model", "deckId"],
      "properties": {
        "model": {
          "description": "Model of the robot this protocol is written for",
          "type": "string",
          "enum": ["OT-2 Standard", "OT-3 Standard"]
        },
        "deckId": {
          "description": "Identifier of physical deck this protocol is written for. This should match a definition in the shared-data directory matching the schema id",
          "type": "string"
        }
      }
    },

    "labwareDefinitionSchemaId": {
      "description": "The schema to use for labware definitions.",
      "type": "string"
    },

    "labwareDefinitions": {
      "description": "All labware definitions used by labware in this protocol, keyed by a unique identifier (definitionId)",
      "patternProperties": {
        ".+": { "type": "object" }
      }
    },

    "liquidSchemaId": {
      "description": "The schema to use for liquid definitions.",
      "type": "string"
    },

    "liquids": {
      "description": "All instances of liquid used in this protocol, keyed by a unique identifier (liquidId)",
      "patternProperties": {
        ".+": { "type": "object" }
      }
    },
    "commandSchemaId": {
      "description": "The schema to which the commands adhere.",
      "type": "string"
    },

    "commands": {
      "description": "An array of command objects representing steps to be executed on the robot.",
      "type": "array",
      "items": { "type": "object" }
    },

    "commandAnnotationSchemaId": {
      "description": "The schema to which the command annotations adhere.",
      "type": "string"
    },

    "commandAnnotations": {
      "type": "array",
      "items": { "type": "object" }
    }
  }
}

=== mrthinger/hardware-hack/opentrons/protocol-designer/fixtures/protocol/8/doItAllV7MigratedToV8.json
{
  "$otSharedSchema": "#/protocol/schemas/8",
  "schemaVersion": 8,
  "metadata": {
    "protocolName": "Flex protocol do it all",
    "author": "",
    "description": "",
    "created": 1689346890165,
    "lastModified": 1718980117330,
    "category": null,
    "subcategory": null,
    "tags": []
  },
  "designerApplication": {
    "name": "opentrons/protocol-designer",
    "version": "8.1.0",
    "data": {
      "_internalAppBuildDate": "Fri, 21 Jun 2024 14:25:33 GMT",
      "defaultValues": {
        "aspirate_mmFromBottom": 1,
        "dispense_mmFromBottom": 1,
        "touchTip_mmFromTop": -1,
        "blowout_mmFromTop": 0
      },
      "pipetteTiprackAssignments": {
        "2e7c6344-58ab-465c-b542-489883cb63fe": [
          "opentrons/opentrons_flex_96_filtertiprack_50ul/1"
        ],
        "6d1e53c3-2db3-451b-ad60-3fe13781a193": [
          "opentrons/opentrons_flex_96_filtertiprack_50ul/1"
        ]
      },
      "dismissedWarnings": {
        "form": [],
        "timeline": []
      },
      "ingredients": {
        "0": {
          "name": "Water",
          "displayColor": "#b925ff",
          "description": null,
          "serialize": false,
          "liquidGroupId": "0"
        },
        "1": {
          "name": "Samples",
          "displayColor": "#ffd600",
          "description": null,
          "serialize": false,
          "liquidGroupId": "1"
        }
      },
      "ingredLocations": {
        "fcba73e7-b88e-438e-963e-f8b9a5de0983:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/2": {
          "A1": {
            "0": {
              "volume": 100
            }
          },
          "B1": {
            "0": {
              "volume": 100
            }
          },
          "C1": {
            "0": {
              "volume": 100
            }
          },
          "D1": {
            "0": {
              "volume": 100
            }
          },
          "E1": {
            "0": {
              "volume": 100
            }
          },
          "F1": {
            "0": {
              "volume": 100
            }
          },
          "G1": {
            "0": {
              "volume": 100
            }
          },
          "H1": {
            "0": {
              "volume": 100
            }
          }
        },
        "a793a135-06aa-4ed6-a1d3-c176c7810afa:opentrons/opentrons_24_aluminumblock_nest_1.5ml_snapcap/1": {
          "A1": {
            "1": {
              "volume": 1000
            }
          }
        }
      },
      "savedStepForms": {
        "__INITIAL_DECK_SETUP_STEP__": {
          "labwareLocationUpdate": {
            "23ed35de-5bfd-4bb0-8f54-da99a2804ed9:opentrons/opentrons_flex_96_filtertiprack_50ul/1": "C1",
            "fcba73e7-b88e-438e-963e-f8b9a5de0983:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/2": "627b7a27-5bb7-46de-a530-67af45652e3b:thermocyclerModuleType",
            "a793a135-06aa-4ed6-a1d3-c176c7810afa:opentrons/opentrons_24_aluminumblock_nest_1.5ml_snapcap/1": "ef44ad7f-0fd9-46d6-8bc0-c70785644cc8:temperatureModuleType",
            "d95bb3be-b453-457c-a947-bd03dc8e56b9:opentrons/opentrons_96_flat_bottom_adapter/1": "c19dffa3-cb34-4702-bcf6-dcea786257d1:heaterShakerModuleType",
            "239ceac8-23ec-4900-810a-70aeef880273:opentrons/nest_96_wellplate_200ul_flat/2": "d95bb3be-b453-457c-a947-bd03dc8e56b9:opentrons/opentrons_96_flat_bottom_adapter/1"
          },
          "pipetteLocationUpdate": {
            "2e7c6344-58ab-465c-b542-489883cb63fe": "left",
            "6d1e53c3-2db3-451b-ad60-3fe13781a193": "right"
          },
          "moduleLocationUpdate": {
            "1be16305-74e7-4bdb-9737-61ec726d2b44:magneticBlockType": "D2",
            "c19dffa3-cb34-4702-bcf6-dcea786257d1:heaterShakerModuleType": "D1",
            "ef44ad7f-0fd9-46d6-8bc0-c70785644cc8:temperatureModuleType": "D3",
            "627b7a27-5bb7-46de-a530-67af45652e3b:thermocyclerModuleType": "B1"
          },
          "stepType": "manualIntervention",
          "id": "__INITIAL_DECK_SETUP_STEP__"
        },
        "236ab92a-24e3-42d8-bad5-cd4cdae9a4c4": {
          "thermocyclerFormType": "thermocyclerProfile",
          "moduleId": "627b7a27-5bb7-46de-a530-67af45652e3b:thermocyclerModuleType",
          "blockIsActive": false,
          "blockTargetTemp": null,
          "lidIsActive": false,
          "lidTargetTemp": null,
          "lidOpen": false,
          "profileVolume": "10",
          "profileTargetLidTemp": "40",
          "orderedProfileItems": [
            "40e2cf7d-112f-4ded-9375-0e225cc776eb",
            "f4aa883f-41e6-42fb-875f-d4adf02fd2c5"
          ],
          "profileItemsById": {
            "40e2cf7d-112f-4ded-9375-0e225cc776eb": {
              "type": "profileStep",
              "id": "40e2cf7d-112f-4ded-9375-0e225cc776eb",
              "title": "tagmentation",
              "temperature": "4",
              "durationMinutes": "1",
              "durationSeconds": ""
            },
            "f4aa883f-41e6-42fb-875f-d4adf02fd2c5": {
              "type": "profileStep",
              "id": "f4aa883f-41e6-42fb-875f-d4adf02fd2c5",
              "title": "hold",
              "temperature": "10",
              "durationMinutes": "2",
              "durationSeconds": ""
            }
          },
          "blockIsActiveHold": false,
          "blockTargetTempHold": null,
          "lidIsActiveHold": false,
          "lidTargetTempHold": null,
          "lidOpenHold": null,
          "id": "236ab92a-24e3-42d8-bad5-cd4cdae9a4c4",
          "stepType": "thermocycler",
          "stepName": "thermocycler",
          "stepDetails": ""
        },
        "2d5ee9a5-c405-4dbc-a57e-2603d709c03d": {
          "thermocyclerFormType": "thermocyclerState",
          "moduleId": "627b7a27-5bb7-46de-a530-67af45652e3b:thermocyclerModuleType",
          "blockIsActive": false,
          "blockTargetTemp": null,
          "lidIsActive": false,
          "lidTargetTemp": null,
          "lidOpen": true,
          "profileVolume": null,
          "profileTargetLidTemp": null,
          "orderedProfileItems": [],
          "profileItemsById": {},
          "blockIsActiveHold": false,
          "blockTargetTempHold": null,
          "lidIsActiveHold": false,
          "lidTargetTempHold": null,
          "lidOpenHold": null,
          "id": "2d5ee9a5-c405-4dbc-a57e-2603d709c03d",
          "stepType": "thermocycler",
          "stepName": "thermocycler",
          "stepDetails": ""
        },
        "f9a294f1-f42b-4cae-893a-592405349d56": {
          "pipette": "2e7c6344-58ab-465c-b542-489883cb63fe",
          "volume": "100",
          "tipRack": "opentrons/opentrons_flex_96_filtertiprack_50ul/1",
          "changeTip": "always",
          "path": "single",
          "aspirate_wells_grouped": false,
          "aspirate_flowRate": null,
          "aspirate_labware": "a793a135-06aa-4ed6-a1d3-c176c7810afa:opentrons/opentrons_24_aluminumblock_nest_1.5ml_snapcap/1",
          "aspirate_wells": ["A1"],
          "aspirate_wellOrder_first": "t2b",
          "aspirate_wellOrder_second": "l2r",
          "aspirate_mix_checkbox": false,
          "aspirate_mix_times": null,
          "aspirate_mix_volume": null,
          "aspirate_mmFromBottom": null,
          "aspirate_touchTip_checkbox": false,
          "aspirate_touchTip_mmFromBottom": null,
          "dispense_flowRate": null,
          "dispense_labware": "fcba73e7-b88e-438e-963e-f8b9a5de0983:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/2",
          "dispense_wells": ["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1"],
          "dispense_wellOrder_first": "t2b",
          "dispense_wellOrder_second": "l2r",
          "dispense_mix_checkbox": false,
          "dispense_mix_times": null,
          "dispense_mix_volume": null,
          "dispense_mmFromBottom": null,
          "dispense_touchTip_checkbox": false,
          "dispense_touchTip_mmFromBottom": null,
          "disposalVolume_checkbox": true,
          "disposalVolume_volume": "100",
          "blowout_checkbox": false,
          "blowout_location": "134504e1-b212-41cf-966d-2560deb5b693:trashBin",
          "preWetTip": false,
          "aspirate_airGap_checkbox": false,
          "aspirate_airGap_volume": "0",
          "aspirate_delay_checkbox": false,
          "aspirate_delay_mmFromBottom": null,
          "aspirate_delay_seconds": "1",
          "dispense_airGap_checkbox": false,
          "dispense_airGap_volume": "50",
          "dispense_delay_checkbox": false,
          "dispense_delay_seconds": "1",
          "dispense_delay_mmFromBottom": null,
          "dropTip_location": "134504e1-b212-41cf-966d-2560deb5b693:trashBin",
          "nozzles": null,
          "dispense_x_position": 0,
          "dispense_y_position": 0,
          "aspirate_x_position": 0,
          "aspirate_y_position": 0,
          "blowout_z_offset": 0,
          "blowout_flowRate": null,
          "id": "f9a294f1-f42b-4cae-893a-592405349d56",
          "stepType": "moveLiquid",
          "stepName": "transfer",
          "stepDetails": ""
        },
        "5fdb9a12-fab4-42fd-886f-40af107b15d6": {
          "times": "2",
          "changeTip": "always",
          "labware": "fcba73e7-b88e-438e-963e-f8b9a5de0983:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/2",
          "mix_wellOrder_first": "t2b",
          "mix_wellOrder_second": "l2r",
          "blowout_checkbox": false,
          "blowout_location": "134504e1-b212-41cf-966d-2560deb5b693:trashBin",
          "mix_mmFromBottom": 0.5,
          "pipette": "6d1e53c3-2db3-451b-ad60-3fe13781a193",
          "volume": "10",
          "wells": ["A1"],
          "aspirate_flowRate": null,
          "dispense_flowRate": null,
          "aspirate_delay_checkbox": false,
          "aspirate_delay_seconds": "1",
          "dispense_delay_checkbox": false,
          "dispense_delay_seconds": "1",
          "mix_touchTip_checkbox": false,
          "mix_touchTip_mmFromBottom": null,
